name: unmaterialistic
description: A custom_lint for warning you against using 'package:flutter/material.dart'.
version: 0.0.3
repository: https://github.com/Luckey-Elijah/unmaterialistic_lint

environment:
  sdk: ^3.11.0

dependencies:
  analyzer: ^10.1.0
  analyzer_plugin: ^0.14.3

dev_dependencies:
  test: ^1.29.0
  very_good_analysis: ^10.2.0
